name: 'python-test-setup'
description: 'installs the required python version and tools'
inputs:
  python-version:
    description: 'python version'
    required: true
    default: 3.8
  tox-version:
    description: 'tox version'
    required: true
    default: 3.24.4
runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install tox==${{ inputs.tox-version }}